export default Object.freeze({
  HOME: '/',
  AUTH: '/auth',
  MENU: '/menu',
  MENU_ITEM: '/menu/:id',
  ORDER_HISTORY: '/order-history',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ACCOUNT: '/account',
  PLANNER: '/planner',
  ABOUT: '/about',
  CONTACT: '/contact',
  DELIVERY: '/delivery',
  FAVOURITES: '/favourites',
});
